services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+pymysql://${MYSQLUSER}:${MYSQLPASSWORD}@mainline.proxy.rlwy.net:48113/${MYSQLDATABASE}"
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - ./backend:/app  # Hot-Reload beim Entwickeln

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backendy
    volumes:
      - ./frontend:/app          # Hot-Reload beim Entwickeln
      - /app/node_modules        # node_modules im Container behalten


